### ISSUE TITLE
Refactor magic number

### ISSUE THREAD

**Issue by Maikon** [eatoncns/ttt_core#1]
https://github.com/eatoncns/ttt_core/blob/56a3c1b4265dd34a258273f04318299d581ab8bf/lib/ttt_core/board.rb#L9

This is one example but there's quite a few places where this happening in the code. See [Replace Magic Number with Symbolic Constant](https://refactoring.com/catalog/replaceMagicNumberWithSymbolicConstant.html).

**Comment by eatoncns** [comment]
I agree where a raw value does not signify it's intent but in this specific case I'm not sure what would be gained? If we have something like the below I think it just adds to the reading burden.

DEFAULT_DIMENSION = 3
def initialize(dimension = DEFAULT_DIMENSION)

**Comment by Maikon** [comment]
Yeah I misread/missed the name there. For this particular instance I agree, no need to change 👍
